### ISSUE TITLE
Postgresql 10 update - It's that time of the year...

### ISSUE THREAD

**Issue by fire** [garethflowers/postgresql-portable#11]
Ping! 

It's Postgresql 10 update time!

**Comment by fire** [comment]
I wonder if you can write a guide how you create the updates. It'll let other people update too.

**Comment by garethflowers** [comment]
v10 releases are in progress - sorry for the delay!

[v10.0.2](https://github.com/garethflowers/postgresql-portable/releases/tag/v10.0.2) now available.

**Comment by g24swint** [comment]
Thanks, Gareth! Hope to try it out soon!
