### ISSUE TITLE
Is postgresql-portable a 32-bit or 64-bit ?

### ISSUE THREAD

**Issue by ncelerier** [garethflowers/postgresql-portable#2]
Hello, 

I have some problems to start Postresql portable. I'm not sure where it might come from, but I would like to know if it is a 32-bit or 64-bit version ? 

On the official Postgresql website, both versions are available.

Regards,
Nicolas.

**Comment by garethflowers** [comment]
PostgreSQL Portable uses the 32bit (x86) versions of PostgreSQL.

**Comment by ncelerier** [comment]
Thank you for your fast answer.
